INSERT INTO TIPOS_DI (TDI_NOME) VALUES ('NOTEBOOKS'), ('MONITORES'),('HUBS'),('SWITCHES'),('ROTEADORES');

INSERT INTO TIPOS_VEICULOS (TVEI_NOME) VALUES ('CARROS'), ('MOTOS'),('CAMINHÕES'),('UTILITÁRIOS');





